### ISSUE TITLE
rook-ceph 1.10.0 国内镜像

### ISSUE THREAD

**Issue by lixie021** [lixie021/lixie021.github.io#5]
# ROOK_CSI_CEPH_IMAGE: "quay.io/cephcsi/cephcsi:v3.7.2"
  # ROOK_CSI_REGISTRAR_IMAGE: "registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0"
  # ROOK_CSI_RESIZER_IMAGE: "registry.k8s.io/sig-storage/csi-resizer:v1.7.0"
  # ROOK_CSI_PROVISIONER_IMAGE: "registry.k8s.io/sig-storage/csi-provisioner:v3.4.0"
  # ROOK_CSI_SNAPSHOTTER_IMAGE: "registry.k8s.io/sig-storage/csi-snapshotter:v6.2.1"
  # ROOK_CSI_ATTACHER_IMAGE: "registry.k8s.io/sig-storage/csi-attacher:v4.1.0"

**Comment by lixie021** [comment]
$ cat operator-patch-v1.10.yaml

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rook-ceph-operator-config
  namespace: rook-ceph
data:
  ROOK_CSI_ATTACHER_IMAGE: uhub.service.ucloud.cn/mirrors/csi-attacher:v4.1.0
#  ROOK_CSI_CEPH_IMAGE: uhub.service.ucloud.cn/mirrors/cephcsi:v3.2.2
  ROOK_CSI_PROVISIONER_IMAGE: uhub.service.ucloud.cn/mirrors/csi-provisioner:v3.4.0
  ROOK_CSI_REGISTRAR_IMAGE: uhub.service.ucloud.cn/mirrors/csi-node-driver-registrar:v2.7.0
  ROOK_CSI_RESIZER_IMAGE: uhub.service.ucloud.cn/mirrors/csi-resizer:v1.7.0
  ROOK_CSI_SNAPSHOTTER_IMAGE: uhub.service.ucloud.cn/mirrors/csi-snapshotter:v6.2.1
```
